version: '3.7'
networks:
  docker_network:
services:
  PHP-SRV:
    image: php-apache-2
    container_name: php-apache
    volumes:
      - ~/work/docker/admin:/var/www/html
      - ~/work/docker/admin/docker/config/apache2.conf:/etc/apache2/apache2.conf
      - ~/work/docker/admin/docker/config/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      #- ~/work/docker/ex3/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - docker_network 
    ports: 
      - '8080:80'
  MYSQL:
    image: mysql:5.7-debian
    volumes:
      - ~/work/docker/volumes/mysql2:/var/lib/mysql
    networks:
      - docker_network 
    environment:
      - MYSQL_ROOT_PASSWORD=root
  PMA:
    image: phpmyadmin
    networks:
      - docker_network 
    ports: 
      - '8090:80'
    environment:
      - PMA_HOST=MYSQL
      - UPLOAD_LIMIT=1G